### ISSUE TITLE
tiny issue in Synthetic_Viewer

### ISSUE THREAD

**Issue by demitch** [geoscixyz/Toolkit#11]
In synthetic notebook 2.1.1 (Synthetic_Viewer to be renamed eventually Synthetic_Response? - see issue 10) for the profile can the x axis have the eastings rather than distance?

![image](https://user-images.githubusercontent.com/39281824/44279305-c648dc00-a205-11e8-86a0-ee6855e880e1.png)

**Comment by fourndo** [comment]
That's hard, because the line can be rotated, so if you are at an angle, it's not really east or north anymore.
We could try to have the true northing and easting lines showing on either side of the plot? Would that work for you?

**Comment by demitch** [comment]
@fourndo oh right, of course ! lets leave it, issue closed!
