### ISSUE TITLE
export of map image (geotiff) to the cloud  - not sure

### ISSUE THREAD

**Issue by demitch** [geoscixyz/Toolkit#124]
I just tested export (or download) of my map from binder, checked the Jupyter output folder and can't see an image, only shape files etc (or are one of these an image?) THere is a tiff there but thats not what I just exported..

![image](https://user-images.githubusercontent.com/39281824/51080377-86d8cb80-168f-11e9-9e78-6d9f4826ca86.png)

**Comment by fourndo** [comment]
Can't reproduce the error. 
![image](https://user-images.githubusercontent.com/2406426/51090185-f18c1480-172c-11e9-957a-7b0a8afb61de.png)

Are you running it local or this from the live app?

**Comment by demitch** [comment]
excuse me, i just pressed the wrong export button. you gotta give me a few free fails here....
