### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by angeleneleow** [geoscixyz/Toolkit#137]
![image](https://user-images.githubusercontent.com/38524055/59132223-74ef1200-8929-11e9-97da-bd4715ae005a.png)
I'm uploading a Geotiff and this error message shows up

**Comment by lheagy** [comment]
👋 Hi @angeleneleow: were you successful in getting back up and running?

**Comment by angeleneleow** [comment]
Hi @lheagy  yes I realised i had NoDataValues that I forgot to key in.
