### ISSUE TITLE
Resizing window in Search filters

### ISSUE THREAD

**Issue by demitch** [geoscixyz/Toolkit#14]
still the problem of the null areas giving error if my new window includes null

![image](https://user-images.githubusercontent.com/39281824/44282546-3a887d00-a210-11e8-9850-4b4045f0d014.png)
![image](https://user-images.githubusercontent.com/39281824/44282560-44aa7b80-a210-11e8-94ca-a6f77b0bca7b.png)

**Comment by fourndo** [comment]
Solved
