### ISSUE TITLE
Magnetic field used for synthetic model

### ISSUE THREAD

**Issue by demitch** [geoscixyz/Toolkit#29]
Just wondering...are we using the Search area magnetic field params for the synthetic model? EPSG code is 26909. Should we keep that or put it at the pole for synthetics? If we keep the Search area field params, should we add an RTP step in the Synthetic Filters notebook 2.1.3.? I dunno the answers! I don't remember if filters are applied to TMI or RTP data in practice?

![image](https://user-images.githubusercontent.com/39281824/44612323-6382b200-a7bc-11e8-9d2c-d3290bdf4cf6.png)

**Comment by fourndo** [comment]
Solved with ```dataGridGeoref``` function
