### ISSUE TITLE
Remove 'refresh' option wherever we have Upward continuation?

### ISSUE THREAD

**Issue by demitch** [geoscixyz/Toolkit#37]
Since the refresh button is to refresh maps to the currently chosen upward continuation distance, we shouldn't require a refresh button on the upward continuation itself (since doesn't do anything for this cell)? I tried to remove that button just for upward continuation but wasn't successful and didn't want to mess around too much!

![image](https://user-images.githubusercontent.com/39281824/44809736-79a9bd00-ab84-11e8-9538-18c6d45742a7.png)

Upward continuation appears in 
Notebook 2.1.3 - synthetic 2D mag filters
Notebook 2.1.4 - synthetic tilt depth
Notebook 2.2.2 - Search 2D mag filters
Notebook 2.2.3 - Search tilt depth

**Comment by fourndo** [comment]
Solved on PR #64
