### ISSUE TITLE
Tilt-depth Notebooks - estimated depth - what does it represent?

### ISSUE THREAD

**Issue by demitch** [geoscixyz/Toolkit#38]
Wondering how to best deal with the 'depth' values coming out here?
Did you say that this was not true depth but actually 'depth' (or distance) from the sensor height?
So if we upward continue we are getting 'depths' relative to the upward continued distance?
Can we calculate the 'true' depth and present it?

![image](https://user-images.githubusercontent.com/39281824/44810805-bfb45000-ab87-11e8-8758-7ae49cecfa86.png)

**Comment by fourndo** [comment]
Solved on PR #63
