### ISSUE TITLE
Related to issue 39, location of exported tiffs

### ISSUE THREAD

**Issue by demitch** [geoscixyz/Toolkit#40]
In addition to customizing the name (and coordinate system????) of these exported grids, where will these exported tiffs/grids get stored and how will users find them? I want to make sure I add that information to the content.

![image](https://user-images.githubusercontent.com/39281824/44816335-d1e9ba80-ab96-11e8-8439-e0829c835b0b.png)

**Comment by fourndo** [comment]
It is currently all sent to the Ouput folder. That way we don't need to version control those files

**Comment by demitch** [comment]
Will the user have an Output folder too? Sorry, I am ignorant on the set-up for the user...

**Comment by fourndo** [comment]
Specified in path
