### ISSUE TITLE
Create User data Notebook/s

### ISSUE THREAD

**Issue by demitch** [geoscixyz/Toolkit#54]
- Import data (any way for an individual to import a geosoft grd??)
- Window subset of data?
- 2D filter suite
- Visualization/shading/color suite
- Tilt depth
- Digitize interps?
- Export options (export as located tiff - specify coord system; located shapefiles for lines)

**Comment by fourndo** [comment]
Begin work on this [commit](https://github.com/geoscixyz/Toolkit/pull/55/commits/dfcbfe3bf66bfdb8e9fc7c0b91c290d813cbfd7e)
