### ISSUE TITLE
Upward continuation slider not working in Search Filter notebook? - for TMI only?

### ISSUE THREAD

**Issue by demitch** [geoscixyz/Toolkit#63]
not sure

![image](https://user-images.githubusercontent.com/39281824/45590421-42aa0a00-b8ed-11e8-885a-395b34bf693c.png)

**Comment by fourndo** [comment]
Fixed on[ PR #64]([https://github.com/geoscixyz/Toolkit/pull/64/commits/7022d169c9e99045ba808e62d77869aeff8654ef])
