### ISSUE TITLE
Turn off select boxes in widgets - Part I

### ISSUE THREAD

**Issue by demitch** [geoscixyz/Toolkit#85]
Certain items the user will not need or can ignore (especially in synthetics). Can work on this after the workshop.... For examples:

In synthetic gridding notebook 2.1.2

![image](https://user-images.githubusercontent.com/39281824/46172944-c05d0680-c259-11e8-9d05-3007fd7e6e5a.png)

In synthetic data visualization 2.1.3

![image](https://user-images.githubusercontent.com/39281824/46173014-f4382c00-c259-11e8-93da-359e238acd68.png)

In synthetic filters 2.1.4

![image](https://user-images.githubusercontent.com/39281824/46173064-192c9f00-c25a-11e8-834f-826602146a7d.png)

in synthetic tilt depth 2.1.5

![image](https://user-images.githubusercontent.com/39281824/46173242-8d674280-c25a-11e8-932b-cff276a7f3fe.png)

**Comment by fourndo** [comment]
Done
