### ISSUE TITLE
Turn off select boxes in widgets - Part II

### ISSUE THREAD

**Issue by demitch** [geoscixyz/Toolkit#87]
These boxes in Search case study could also be hidden?

Search notebooks 2.2.1, and 2.2.2, and 2.2.3.

![image](https://user-images.githubusercontent.com/39281824/46179963-a11ea300-c272-11e8-8645-71d2f2b98a72.png)

and here (keep reduced to pole button):

![image](https://user-images.githubusercontent.com/39281824/46180000-c6131600-c272-11e8-8fc9-98a4d41c6160.png)

**Comment by fourndo** [comment]
I froze the EPSG, Inc and Dec for the second one, but I think we should keep the other one as is, cause people might want to export it still
